### PR TITLE
started orm implementation

### LINKED ISSUE #2: Migration to SqlAlchemy v1.4
SqlAlchemy v1.4 is currently in beta but is expected to release during development.
To future proof the application I think it will be necessary to migrate. Espacially since
v1.4 is a stepping stone to v2.0 and is suppossed to be compatible with it.
Possible changes include:
* select takes columns as args and not List of columns

### LINKED ISSUE #3: Database class rework
I can already see the event database getting very messy the way it is encoded now
I suggest keeping the class by only encoding basic queries in sing tabels (get, set, etc).
More complex queries can then be done via alibrary in which every function takes
the db class as argument or and querry manager, a class that manages more complex queries.

### PR DESCRIPTION
**Pull request by DSMaVie**
This is the new version of the db implementation.
closes #3
closes #2

### CODE REVIEW

**Comment by DSMaVie** [comment]
Okay, Today I started work on the reworkof the databases. `schema.py` now includes a Abstract Base TableClass which all other classes inherit from and the table classes for our 4 classes. The query manager then acts like a session manager opening and closing transactions on the database and enacting queries in between. The logic is pretty neat so far.
Work still to be done:
* Insert Recurring Event
* Insert Template
* get complete event data

Improvements for later ( make new issues before accepting PR):
* Use Relationship API for realtions between tables
* Build stronger constraints on regularities table

**Comment by DSMaVie** [comment]
Okay so I`ve concluded the rework it looks neater now. It at least gives is some dummy data to work with in the frontend. I`ve found that the biggest problems arose from not using the relationship api. it really makes joining hard using the orm. not sure if we need joins for that anyway then. -> maybe using the relationship api we only need a function unpack for events and such. I guess we leave it open for now the joins are done using plain old sql syntax in text form.

**Comment by DSMaVie** [comment]
nut sure what happens if I click on squash and merge. does it merge or wait for your review?

**Review by AlexLukasT — APPROVED** [review]
I think reviewing is optional and you can still merge nevertheless

**Pull request merged**
